# Generated by Django 5.0 on 2023-12-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, max_length=400, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата выполнения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.URLField(max_length=1000, verbose_name='Изображение')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='articles', to='shop.typearticle', verbose_name='Тип')),
            ],
        ),
    ]
