# Generated by Django 4.2.7 on 2023-12-26 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_article_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.article')),
            ],
        ),
    ]
